

default:
	@bash make_composite_track_stanza.sh embryo_intestine_cells_merged 'embryo intestine RNA-seq' 'embryo intestine GFP+ sorted cells RNA-seq'
	@bash make_composite_track_stanza.sh L1_intestine_cells_merged 'L1 intestine RNA-seq' 'L1 intestine GFP+ sorted cells RNA-seq'
	@bash make_composite_track_stanza.sh L3_intestine_cells_merged 'L3 intestine RNA-seq' 'L3 intestine GFP+ sorted cells RNA-seq'

